---
name: 'Flutter C++ Packager - Android 16+'
description: >-
  A GitHub Action to build and package Flutter applications
  with C++ components, targeting Android 16+ on Windows VM
author: 'Binah-Arbitor'
branding:
  icon: 'package'
  color: 'blue'

inputs:
  flutter-version:
    description: 'Flutter SDK version to use'
    required: false
    default: 'stable'
  flutter-channel:
    description: 'Flutter channel (stable, beta, dev, master)'
    required: false
    default: 'stable'
  target-platform:
    description: 'Target platform (android, ios, linux, windows, macos, web)'
    required: true
  build-mode:
    description: 'Build mode (debug, profile, release)'
    required: false
    default: 'release'
  cpp-compiler:
    description: 'C++ compiler to use (gcc, clang, msvc)'
    required: false
    default: 'gcc'
  output-path:
    description: 'Output path for packaged application'
    required: false
    default: './dist'
  app-name:
    description: 'Application name for packaging'
    required: true
  include-cpp-libs:
    description: 'Include C++ libraries in package'
    required: false
    default: 'true'

outputs:
  package-path:
    description: 'Path to the generated package'
    value: ${{ steps.package.outputs.path }}
  package-size:
    description: 'Size of the generated package'
    value: ${{ steps.package.outputs.size }}

runs:
  using: 'composite'
  steps:
    - name: Setup Flutter (Channel-based)
      uses: subosito/flutter-action@v4
      if: >-
        ${{ inputs.flutter-version == 'stable' ||
            inputs.flutter-version == 'beta' ||
            inputs.flutter-version == 'dev' ||
            inputs.flutter-version == 'master' }}
      with:
        channel: ${{ inputs.flutter-version }}

    - name: Setup Flutter (Version-based)
      uses: subosito/flutter-action@v4
      if: >-
        ${{ inputs.flutter-version != 'stable' &&
            inputs.flutter-version != 'beta' &&
            inputs.flutter-version != 'dev' &&
            inputs.flutter-version != 'master' }}
      with:
        flutter-version: ${{ inputs.flutter-version }}

    - name: Check and Install Dependencies
      shell: bash
      run: |
        echo "🔍 Running dependency check..."
        ${{ github.action_path }}/scripts/check-dependencies.sh

    - name: Setup C++ Environment
      shell: bash
      run: |
        echo "🔧 Setting up C++ build environment..."

        # Function to get latest Crypto++ version
        get_latest_cryptopp_version() {
          # Try to get latest version from GitHub, fallback to known stable version
          LATEST_VERSION=$(curl -s https://github.com/weidai11/cryptopp/releases \
            2>/dev/null | grep -o 'CRYPTOPP_[0-9_]*' | head -1 || echo "")
          if [ -z "$LATEST_VERSION" ]; then
            LATEST_VERSION="CRYPTOPP_8_9_0"  # Fallback to known stable version
          fi
          echo "$LATEST_VERSION"
        }

        # Function to build crypto++ from source with latest version
        build_cryptopp_from_source() {
          echo "📥 Building Crypto++ from source..."
          cd /tmp
          CRYPTO_VERSION=$(get_latest_cryptopp_version)
          CRYPTO_ZIP_VERSION=$(echo $CRYPTO_VERSION | sed 's/CRYPTOPP_//g' | \
            sed 's/_//g')
          echo "🔄 Using Crypto++ version: $CRYPTO_VERSION ($CRYPTO_ZIP_VERSION)"

          # Download and extract
          wget https://github.com/weidai11/cryptopp/releases/download/${CRYPTO_VERSION}/cryptopp${CRYPTO_ZIP_VERSION}.zip
          unzip cryptopp${CRYPTO_ZIP_VERSION}.zip -d cryptopp
          cd cryptopp

          # Build and install
          if [ "${{ runner.os }}" = "Linux" ]; then
            make -j$(nproc)
            sudo make install PREFIX=/usr/local
            sudo ldconfig
          elif [ "${{ runner.os }}" = "macOS" ]; then
            make -j$(sysctl -n hw.ncpu)
            sudo make install PREFIX=/usr/local
          fi

          echo "✅ Built and installed Crypto++ $CRYPTO_VERSION from source"
        }

        if [ "${{ runner.os }}" = "Linux" ]; then
          echo "📦 Installing Linux dependencies..."
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build pkg-config libgtk-3-dev mesa-utils

          # Try to install crypto++ library with multiple package names
          CRYPTO_INSTALLED=false

          # Try primary package name
          if sudo apt-get install -y libcrypto++-dev; then
            echo "✅ Installed libcrypto++-dev package"
            CRYPTO_INSTALLED=true
          else
            echo "⚠️  libcrypto++-dev package not available, trying alternatives..."

            # Try alternative package names
            if sudo apt-get install -y libcrypto++8-dev 2>/dev/null; then
              echo "✅ Installed libcrypto++8-dev"
            elif sudo apt-get install -y libcryptoppdev 2>/dev/null; then
              echo "✅ Installed libcryptoppdev"
            elif sudo apt-get install -y libcryptopp-dev 2>/dev/null; then
              echo "✅ Installed libcryptopp-dev"
            else
              echo "📥 Installing crypto++ from source (using latest version)..."
              build_cryptopp_from_source
            fi
          fi

          # Verify installation
          echo "🔍 Verifying crypto++ installation..."
          CRYPTO_VERIFIED=false

          # Method 1: Check pkg-config
          if pkg-config --exists libcrypto++; then
            echo "✅ pkg-config found libcrypto++ v$(pkg-config --modversion libcrypto++)"
            CRYPTO_VERIFIED=true
          elif pkg-config --exists cryptopp; then
            echo "✅ pkg-config found cryptopp v$(pkg-config --modversion cryptopp)"
            CRYPTO_VERIFIED=true
          fi

          # Method 2: Check headers
          if [ -f "/usr/include/cryptopp/cryptlib.h" ] || [ -f "/usr/local/include/cryptopp/cryptlib.h" ]; then
            echo "✅ Crypto++ headers found"
            CRYPTO_VERIFIED=true
          fi

          # Method 3: Check libraries
          if find /usr /usr/local -name "*crypto*" -type f 2>/dev/null | grep -E "\.(so|a|dylib)$" | grep -v openssl | head -1; then
            echo "✅ Crypto++ library files found"
            CRYPTO_VERIFIED=true
          fi

          if [ "$CRYPTO_VERIFIED" = "true" ]; then
            echo "✅ Crypto++ library verification successful"
          else
            echo "❌ Crypto++ library verification failed"
            echo "📋 Debugging information:"
            echo "Available packages:"
            pkg-config --list-all | grep -i crypto || echo "No crypto packages found"
            echo "Library files:"
            find /usr -name "*crypto*" -type f 2>/dev/null | head -5 || echo "No crypto files found"
            exit 1
          fi
        elif [ "${{ runner.os }}" = "macOS" ]; then
          echo "📦 Installing macOS dependencies..."
          brew install cmake ninja pkg-config

          # Try to install crypto++ via Homebrew
          if brew install cryptopp; then
            echo "✅ Installed cryptopp via Homebrew"
          else
            echo "⚠️  Homebrew cryptopp not available, building from source..."
            build_cryptopp_from_source
          fi

        elif [ "${{ runner.os }}" = "Windows" ]; then
          echo "📦 Installing Windows dependencies..."
          choco install cmake ninja

          # Check if vcpkg is available
          if command -v vcpkg >/dev/null 2>&1; then
            echo "📦 Installing crypto++ via vcpkg..."
            vcpkg install cryptopp:x64-windows
            echo "✅ Installed cryptopp via vcpkg"
          else
            echo "📥 Setting up vcpkg and installing crypto++..."
            cd /tmp
            git clone https://github.com/Microsoft/vcpkg.git
            cd vcpkg
            ./bootstrap-vcpkg.bat
            ./vcpkg install cryptopp:x64-windows
            echo "VCPKG_ROOT=/tmp/vcpkg" >> $GITHUB_ENV
            echo "CMAKE_TOOLCHAIN_FILE=/tmp/vcpkg/scripts/buildsystems/vcpkg.cmake" >> $GITHUB_ENV
            echo "✅ Installed crypto++ via vcpkg"
          fi
        fi

        # Comprehensive verification of Crypto++ installation
        echo ""
        echo "🔍 Verifying Crypto++ installation..."
        VERIFICATION_PASSED=false

        # Check via pkg-config
        if pkg-config --exists libcrypto++; then
          echo "✅ pkg-config libcrypto++: $(pkg-config --modversion libcrypto++)"
          VERIFICATION_PASSED=true
        elif pkg-config --exists cryptopp; then
          echo "✅ pkg-config cryptopp: $(pkg-config --modversion cryptopp)"
          VERIFICATION_PASSED=true
        fi

        # Check for headers
        for header_path in /usr/include/cryptopp /usr/local/include/cryptopp /usr/include/crypto++ /usr/local/include/crypto++ /opt/homebrew/include/cryptopp; do
          if [ -f "$header_path/cryptlib.h" ]; then
            echo "✅ Found Crypto++ headers: $header_path/cryptlib.h"
            VERIFICATION_PASSED=true
            break
          fi
        done

        # Check for libraries
        for lib_path in /usr/lib /usr/local/lib /opt/homebrew/lib /usr/lib/x86_64-linux-gnu /usr/lib/aarch64-linux-gnu; do
          if [ -f "$lib_path/libcryptopp.so" ] || [ -f "$lib_path/libcrypto++.so" ] || [ -f "$lib_path/libcryptopp.a" ] || [ -f "$lib_path/libcryptopp.dylib" ]; then
            echo "✅ Found Crypto++ library in: $lib_path"
            VERIFICATION_PASSED=true
            break
          fi
        done

        if [ "$VERIFICATION_PASSED" = false ]; then
          echo "❌ Crypto++ library verification failed!"
          echo "📋 Available libraries:"
          find /usr /usr/local /opt -name "*crypto*" -type f 2>/dev/null | grep -E "\.(so|a|dylib|lib)$" | head -10 || echo "No crypto libraries found"
          exit 1
        fi

        echo "✅ Crypto++ library verification successful!"

        echo ""
        echo "🔍 Final verification - checking for crypto++ installation..."
        echo "📋 Library search results:"
        find /usr /usr/local /opt -name "*crypto*" -type f 2>/dev/null | grep -E "\.(so|a|dylib|lib)$" | head -5 || echo "No crypto libraries found in standard paths"

    - name: Install Flutter Dependencies
      shell: bash
      run: |
        echo "Installing Flutter dependencies..."
        flutter pub get
        flutter doctor -v

    - name: Build C++ Components
      shell: bash
      run: |
        echo "Building C++ components..."
        ${{ github.action_path }}/scripts/build-cpp.sh "${{ inputs.cpp-compiler }}" "${{ inputs.target-platform }}"

    - name: Build Flutter Application
      shell: bash
      run: |
        echo "Building Flutter application for ${{ inputs.target-platform }}..."
        
        # Configure Android API levels for Android 16+ support if targeting Android
        if [ "${{ inputs.target-platform }}" = "android" ]; then
          echo "Configuring Android API levels for Android 16+ support..."
          
          # Check if android/app/build.gradle exists
          if [ -f "android/app/build.gradle" ]; then
            echo "Updating Android configuration to target Android 16+ (API level 16)..."
            
            # Update minSdkVersion to 16 (Android 4.1+) to support Android 16+
            sed -i.bak -E 's/minSdkVersion [0-9]+/minSdkVersion 16/g' android/app/build.gradle
            sed -i.bak -E 's/minSdkVersion = [0-9]+/minSdkVersion = 16/g' android/app/build.gradle
            sed -i.bak -E 's/minSdk [0-9]+/minSdk 16/g' android/app/build.gradle
            sed -i.bak -E 's/minSdk = [0-9]+/minSdk = 16/g' android/app/build.gradle
            
            # Keep modern targetSdkVersion and compileSdkVersion for latest features
            sed -i.bak -E 's/targetSdkVersion [0-9]+/targetSdkVersion 34/g' android/app/build.gradle
            sed -i.bak -E 's/targetSdkVersion = [0-9]+/targetSdkVersion = 34/g' android/app/build.gradle
            sed -i.bak -E 's/targetSdk [0-9]+/targetSdk 34/g' android/app/build.gradle
            sed -i.bak -E 's/targetSdk = [0-9]+/targetSdk = 34/g' android/app/build.gradle
            
            sed -i.bak -E 's/compileSdkVersion [0-9]+/compileSdkVersion 34/g' android/app/build.gradle
            sed -i.bak -E 's/compileSdkVersion = [0-9]+/compileSdkVersion = 34/g' android/app/build.gradle
            sed -i.bak -E 's/compileSdk [0-9]+/compileSdk 34/g' android/app/build.gradle  
            sed -i.bak -E 's/compileSdk = [0-9]+/compileSdk = 34/g' android/app/build.gradle
            
            echo "✅ Android configuration updated for Android 16+ support"
            echo "   - minSdkVersion: 16 (Android 4.1+)"
            echo "   - targetSdkVersion: 34 (Android 14)"
            echo "   - compileSdkVersion: 34 (Android 14)"
          else
            echo "⚠️ build.gradle not found, will use Flutter defaults"
          fi
        fi
        
        ${{ github.action_path }}/scripts/build-flutter.sh "${{ inputs.target-platform }}" "${{ inputs.build-mode }}"

    - name: Package Application
      id: package
      shell: bash
      run: |
        echo "Packaging application..."
        ${{ github.action_path }}/scripts/package.sh "${{ inputs.target-platform }}" "${{ inputs.app-name }}" "${{ inputs.output-path }}" "${{ inputs.include-cpp-libs }}"

    - name: Test Built Libraries
      shell: bash
      run: |
        echo "Testing built C++ libraries..."
        ${{ github.action_path }}/scripts/test-libraries.sh
