---
name: cryptingtool
description: A Flutter application with C++ cryptographic components targeting Android 16+

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  # C++ Integration
  ffi: ^2.1.0
  path: ^1.8.3

  # UI Components
  cupertino_icons: ^1.0.6
  file_picker: ^8.0.0+1

  # State Management
  provider: ^6.1.1

  # Fonts and Styling
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
