name: cryptingtool
description: A Flutter application with C++ cryptographic components

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  # C++ Integration
  ffi: ^2.1.2
  path: ^1.9.0

  # UI Components  
  cupertino_icons: ^1.0.8
  file_picker: ^8.0.7

  # State Management
  provider: ^6.1.2

  # Fonts and Styling
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/