name: cryptingtool
description: A Flutter application with C++ integration for cryptographic operations.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  ffigen: ^11.0.0

flutter:
  uses-material-design: true

ffigen:
  output: 'lib/crypto_bindings.dart'
  headers:
    entry-points:
      - 'native/crypto.h'
  name: 'CryptoBindings'
  description: 'Bindings for crypto native library'