# 워크플로우의 이름
name: Android CI - Build Debug APK

# 워크플로우가 실행될 조건
on:
  # main 브랜치에 push가 발생했을 때
  push:
    branches: [ "main" ]
  # 수동으로 실행할 수 있도록 workflow_dispatch 추가
  workflow_dispatch:

# 실행될 작업들
jobs:
  build:
    # 작업이 실행될 가상 환경
    runs-on: ubuntu-latest

    # 작업의 단계들
    steps:
      # 1. 레포지토리 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. JDK 17 설정 (프로젝트의 build.gradle에 맞춰 설정)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # 3. gradlew 실행 권한 부여 (필수)
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. Gradle을 사용하여 디버그 APK 빌드
      - name: Build with Gradle
        run: ./gradlew assembleDebug

      # 5. 생성된 APK를 아티팩트(Artifact)로 업로드
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          # APK가 생성되는 기본 경로
          path: app/build/outputs/apk/debug/app-debug.apk
