name: Test Flutter C++ Packager

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-linux:
    runs-on: ubuntu-latest
    name: Test Linux Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Test Flutter C++ Packager
        uses: ./
        with:
          target-platform: 'linux'
          app-name: 'CryptingTool'
          build-mode: 'release'
          flutter-version: 'stable'
          output-path: './test-output'
        id: test-build
        
      - name: Verify Output
        run: |
          echo "Package created at: ${{ steps.test-build.outputs.package-path }}"
          echo "Package size: ${{ steps.test-build.outputs.package-size }}"
          ls -la ./test-output
          
      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-test-package
          path: ${{ steps.test-build.outputs.package-path }}

  test-multi-platform:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            platform: linux
          - os: windows-latest
            platform: windows
          - os: macos-latest
            platform: macos
    
    runs-on: ${{ matrix.os }}
    name: Test ${{ matrix.platform }} Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Test Platform Build
        uses: ./
        with:
          target-platform: ${{ matrix.platform }}
          app-name: 'CryptingTool-${{ matrix.platform }}'
          build-mode: 'release'
          output-path: './packages'
        id: platform-build
        
      - name: Upload Platform Package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-package
          path: ${{ steps.platform-build.outputs.package-path }}